(define (prim n)
  (asm-8 (+ #xc0 n)))

(define (default-prim->number pri)
  (case pri
    ((#%number?)         (prim 0))
    ((#%+)               (prim 1))
    ((#%-)               (prim 2))
    ((#%mul-non-neg)     (prim 3))
    ((#%quotient)        (prim 4))
    ((#%remainder)       (prim 5))
    ((#%=)               (prim 7))
    ((#%<)               (prim 8))
    ((#%>)               (prim 10))
    ((#%pair?)           (prim 12))
    ((#%cons)            (prim 13))
    ((#%car)             (prim 14))
    ((#%cdr)             (prim 15))
    ((#%set-car!)        (prim 16))
    ((#%set-cdr!)        (prim 17))
    ((#%null?)           (prim 18))
    ((#%eq?)             (prim 19))
    ((#%not)             (prim 20))
    ((#%get-cont)        (prim 21))
    ((#%graft-to-cont)   (prim 22))
    ((#%return-to-cont)  (prim 23))
    ((#%halt)            (prim 24))
    ((#%symbol?)         (prim 25))
    ((#%string?)         (prim 26))
    ((#%string->list)    (prim 27))
    ((#%list->string)    (prim 28))
    ((#%make-u8vector)   (prim 29))
    ((#%u8vector-ref)    (prim 30))
    ((#%u8vector-set!)   (prim 31))
    ((#%print)           (prim 32))
    ((#%clock)           (prim 33))
    ((#%motor)           (prim 34))
    ((#%led)             (prim 35))
    ((#%led2-color)      (prim 36))
    ((#%getchar-wait )   (prim 37))
    ((#%putchar)         (prim 38))
    ((#%beep)            (prim 39))
    ((#%adc)             (prim 40))
    ((#%u8vector?)       (prim 41))
    ((#%sernum)          (prim 42))
    ((#%u8vector-length) (prim 43))
    ((#%boolean?)        (prim 48))
    ((#%network-init)    (prim 49))
    ((#%network-cleanup) (prim 50))
    ((#%receive-packet-to-u8vector) (prim 51))
    ((#%send-packet-from-u8vector)  (prim 52))
    ((#%ior)             (prim 53))
    ((#%xor)             (prim 54))
    ('shift                         (prim 45))
    ('pop                           (prim 46))
    ('return                        (prim 47))
    ('boolean?                      (prim 48))
    (else
     (compiler-error "unknown primitive" pri))))

